FROM node
RUN npm install nodemon -g
RUN mkdir /src
#COPY . /src
WORKDIR /src
Copy package.json package.json
RUN npm install
COPY . .
EXPOSE 4000
EXPOSE 5858
RUN npm install
ENTRYPOINT nodemon --debug -L server.js
#ENTRYPOINT nodemon server.js